### DS DL Internship 16/6/25, Parth Gawad

#### Multiply all the odd numbers in the given list

In [6]:
randomlist = [1,2,3,4,5]
result = 1
for _ in randomlist : 
    if _ % 2 != 0 :
        result *= _
print(f'The final answer is : {result}');

The final answer is : 15


#### Multiply all the even numbers in the given list

In [8]:
randomlist = [1,2,3,4,5]
result = 1
for _ in randomlist : 
    if _ % 2 != 1 :
        result *= _
print(f'The final answer is : {result}');

The final answer is : 8


### Numpy

In [10]:
import numpy as np
inputarr = np.array ([
    [1,2,3],
    [4,5,6]
])
inputarr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
inputarr.shape


(2, 3)

In [14]:
inputarr[1][1]

np.int64(5)

In [15]:
inputarr[0][1:]

array([2, 3])

#### Sorting the array

In [16]:
arr = np.array([1200,34,2,62,2])
np.sort(arr)

array([   2,    2,   34,   62, 1200])

#### Reshape the array 

In [18]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [19]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]
